import Shoe1 from "@/assets/discount/s1.jpeg";
import Shoe2 from "@/assets/discount/s2.jpeg";
import Shoe3 from "@/assets/discount/s3.jpeg";
import Shoe4 from "@/assets/discount/s4.jpeg";
import Shoe5 from "@/assets/discount/s5.jpeg";
// Additional import placeholders - you'll need to add actual image files
import Shoe6 from "@/assets/discount/s1.jpeg";
import Shoe7 from "@/assets/discount/s2.jpeg";
import Shoe8 from "@/assets/discount/s3.jpeg";
import Shoe9 from "@/assets/discount/s4.jpeg";
import Shoe10 from "@/assets/discount/s5.jpeg";
import Shoe11 from "@/assets/discount/s1.jpeg";
import Shoe12 from "@/assets/discount/s2.jpeg";
import Shoe13 from "@/assets/discount/s3.jpeg";
import Shoe14 from "@/assets/discount/s4.jpeg";
import Shoe15 from "@/assets/discount/s5.jpeg";

export const shoesData = [
  // Original shoes (1-5)
  {
    id: 1,
    name: "Nike Air Max 270",
    price: 150,
    image: Shoe1,
    gallery: [
      "https://example.com/nike-air-max-270-angle1.jpg",
      "https://example.com/nike-air-max-270-angle2.jpg",
      "https://example.com/nike-air-max-270-sole.jpg",
    ],
    category: "casual",
    brand: "Nike",
    rating: 4.8,
    reviewCount: 235,
    isNew: true,
    discount: null,
    description:
      "The Nike Air Max 270 delivers a plush ride and modern look. The first-ever Max Air unit designed specifically for Nike lifestyle shoes offers all-day comfort.",
    colors: [
      { name: "Black", value: "black", hex: "#000000" },
      { name: "White", value: "white", hex: "#FFFFFF" },
      { name: "Red", value: "red", hex: "#FF0000" },
    ],
    sizes: [7, 8, 9, 10, 11, 12],
    styles: ["Athletic", "Casual"],
    features: [
      "Max Air 270 unit delivers unrivaled, all-day comfort",
      "Mesh upper for optimal breathability",
      "Foam midsole for responsive cushioning",
      "Rubber outsole for durability and traction",
    ],
  },
  {
    id: 2,
    name: "Puma RS-X",
    price: 110,
    image: Shoe2,
    gallery: [
      "https://example.com/puma-rs-x-angle1.jpg",
      "https://example.com/puma-rs-x-angle2.jpg",
    ],
    category: "casual",
    brand: "Puma",
    rating: 4.7,
    reviewCount: 180,
    isNew: true,
    discount: null,
    description: "Bold and vibrant sneakers for active men.",
    colors: [
      { name: "Black", value: "black", hex: "#000000" },
      { name: "White", value: "white", hex: "#FFFFFF" },
      { name: "Red", value: "red", hex: "#FF0000" },
    ],
    sizes: [40, 41, 42, 43, 44, 45],
    styles: ["Sport", "Casual"],
    features: [
      "Cushioned footbed for comfort",
      "Lightweight and breathable mesh upper",
      "Durable rubber outsole for traction",
      "Bold, eye-catching design",
    ],
  },
  {
    id: 3,
    name: "Nike Free Run",
    price: 100,
    image: Shoe3,
    gallery: [
      "https://example.com/nike-free-run-angle1.jpg",
      "https://example.com/nike-free-run-angle2.jpg",
    ],
    category: "casual",
    brand: "Nike",
    rating: 4.4,
    reviewCount: 210,
    isNew: false,
    discount: 17,
    description: "Versatile running shoes for flexibility and comfort.",
    colors: [
      { name: "Gray", value: "gray", hex: "#808080" },
      { name: "Black", value: "black", hex: "#000000" },
      { name: "Red", value: "red", hex: "#FF0000" },
    ],
    sizes: [39, 40, 41, 42, 43],
    styles: ["Running", "Casual"],
    features: [
      "Flexible outsole for enhanced movement",
      "Breathable mesh upper for ventilation",
      "Responsive cushioning for all-day comfort",
      "Lightweight and minimalistic design",
    ],
  },
  {
    id: 4,
    name: "Adidas Ultraboost",
    price: 140,
    image: Shoe4,
    gallery: [
      "https://example.com/adidas-ultraboost-angle1.jpg",
      "https://example.com/adidas-ultraboost-angle2.jpg",
    ],
    category: "casual",
    brand: "Adidas",
    rating: 4.8,
    reviewCount: 150,
    isNew: false,
    discount: 12,
    description: "Ultra-comfortable sneakers with a responsive boost midsole.",
    colors: [
      { name: "White", value: "white", hex: "#FFFFFF" },
      { name: "Black", value: "black", hex: "#000000" },
      { name: "Blue", value: "blue", hex: "#0000FF" },
    ],
    sizes: [40, 41, 42, 43, 44],
    styles: ["Sport", "Casual"],
    features: [
      "Boost midsole for energy return",
      "Breathable knit upper for ventilation",
      "Durable rubber outsole for traction",
      "Flexible and cushioned fit",
    ],
  },
  {
    id: 5,
    name: "Adidas NMD",
    price: 125,
    image: Shoe5,
    gallery: [
      "https://example.com/adidas-nmd-angle1.jpg",
      "https://example.com/adidas-nmd-angle2.jpg",
    ],
    category: "running",
    brand: "Adidas",
    rating: 4.6,
    reviewCount: 180,
    isNew: true,
    discount: 17,
    description: "Modern sneakers with a sleek design for all-day comfort.",
    colors: [
      { name: "Black", value: "black", hex: "#000000" },
      { name: "White", value: "white", hex: "#FFFFFF" },
      { name: "Gray", value: "gray", hex: "#808080" },
    ],
    sizes: [40, 41, 42, 43, 44],
    styles: ["Athletic", "Casual"],
    features: [
      "Responsive Boost cushioning for comfort",
      "Breathable mesh upper",
      "Sleek, contemporary design",
      "Rubber outsole for durability and grip",
    ],
  },

  // Women's shoes
  {
    id: 6,
    name: "Nike Air Zoom Pegasus",
    price: 120,
    image: Shoe6,
    gallery: [
      "https://example.com/nike-air-zoom-pegasus-angle1.jpg",
      "https://example.com/nike-air-zoom-pegasus-angle2.jpg",
    ],
    category: "womens",
    brand: "Nike",
    rating: 4.7,
    reviewCount: 189,
    isNew: true,
    discount: null,
    description: "Versatile women's running shoes for everyday training.",
    colors: [
      { name: "Pink", value: "pink", hex: "#FFC0CB" },
      { name: "Blue", value: "blue", hex: "#0000FF" },
      { name: "Black", value: "black", hex: "#000000" },
    ],
    sizes: [5, 6, 7, 8, 9, 10],
    styles: ["Running", "Sport"],
    features: [
      "Responsive Zoom Air cushioning",
      "Engineered mesh upper for targeted breathability",
      "Durable rubber outsole for traction on multiple surfaces",
      "Secure fit with Flywire technology",
    ],
  },
  {
    id: 7,
    name: "Adidas Cloudfoam Pure",
    price: 80,
    image: Shoe7,
    gallery: [
      "https://example.com/adidas-cloudfoam-pure-angle1.jpg",
      "https://example.com/adidas-cloudfoam-pure-angle2.jpg",
    ],
    category: "running",
    brand: "Adidas",
    rating: 4.6,
    reviewCount: 210,
    isNew: false,
    discount: 15,
    description: "Slip-on women's shoes with exceptional comfort and style.",
    colors: [
      { name: "White", value: "white", hex: "#FFFFFF" },
      { name: "Gray", value: "gray", hex: "#808080" },
      { name: "Purple", value: "purple", hex: "#800080" },
    ],
    sizes: [5, 6, 7, 8, 9],
    styles: ["Casual", "Athletic"],
    features: [
      "Cloudfoam memory sockliner for step-in comfort",
      "Soft textile upper for lightweight feel",
      "Slip-on construction for easy on and off",
      "Memory foam footbed molds to your foot",
    ],
  },
  {
    id: 8,
    name: "New Balance Fresh Foam 1080",
    price: 150,
    image: Shoe8,
    gallery: [
      "https://example.com/new-balance-fresh-foam-1080-angle1.jpg",
      "https://example.com/new-balance-fresh-foam-1080-angle2.jpg",
    ],
    category: "womens",
    brand: "New Balance",
    rating: 4.8,
    reviewCount: 155,
    isNew: true,
    discount: null,
    description: "Premium women's running shoes with maximum cushioning.",
    colors: [
      { name: "Turquoise", value: "turquoise", hex: "#40E0D0" },
      { name: "Black", value: "black", hex: "#000000" },
      { name: "Gray", value: "gray", hex: "#808080" },
    ],
    sizes: [6, 7, 8, 9, 10],
    styles: ["Running", "running"],
    features: [
      "Fresh Foam midsole for plush cushioning",
      "Hypoknit upper for strategic stretch and support",
      "Ultra Heel design hugs the back of the foot",
      "Ortholite sockliner for premium underfoot comfort",
    ],
  },

  // Kids' shoes
  {
    id: 9,
    name: "Nike Air Force 1 Kids",
    price: 75,
    image: Shoe9,
    gallery: [
      "https://example.com/nike-air-force-1-kids-angle1.jpg",
      "https://example.com/nike-air-force-1-kids-angle2.jpg",
    ],
    category: "kids",
    brand: "Nike",
    rating: 4.7,
    reviewCount: 90,
    isNew: false,
    discount: 10,
    description: "Classic sneaker style sized for growing feet.",
    colors: [
      { name: "White", value: "white", hex: "#FFFFFF" },
      { name: "Black", value: "black", hex: "#000000" },
      { name: "Blue", value: "blue", hex: "#0000FF" },
    ],
    sizes: [3, 3.5, 4, 4.5, 5, 5.5, 6],
    styles: ["Casual", "Sport"],
    features: [
      "Durable leather upper for support",
      "Foam midsole for lightweight cushioning",
      "Perforations for added breathability",
      "Non-marking rubber outsole for durability and traction",
    ],
  },
  {
    id: 10,
    name: "Adidas Fortarun Kids",
    price: 60,
    image: Shoe10,
    gallery: [
      "https://example.com/adidas-fortarun-kids-angle1.jpg",
      "https://example.com/adidas-fortarun-kids-angle2.jpg",
    ],
    category: "kids",
    brand: "Adidas",
    rating: 4.5,
    reviewCount: 72,
    isNew: true,
    discount: null,
    description: "Supportive running shoes designed for active kids.",
    colors: [
      { name: "Red", value: "red", hex: "#FF0000" },
      { name: "Blue", value: "blue", hex: "#0000FF" },
      { name: "Black", value: "black", hex: "#000000" },
    ],
    sizes: [11, 12, 13, 1, 2, 3],
    styles: ["Running", "Sport"],
    features: [
      "Cloudfoam midsole for cushioning",
      "Breathable mesh upper keeps feet cool",
      "Hook-and-loop closure for easy on and off",
      "Durable outsole for playground resilience",
    ],
  },

  // Sport shoes
  {
    id: 11,
    name: "Under Armour HOVR Phantom",
    price: 130,
    image: Shoe11,
    gallery: [
      "https://example.com/under-armour-hovr-phantom-angle1.jpg",
      "https://example.com/under-armour-hovr-phantom-angle2.jpg",
    ],
    category: "sport",
    brand: "Under Armour",
    rating: 4.6,
    reviewCount: 128,
    isNew: true,
    discount: null,
    description:
      "High-performance running shoes with energy return technology.",
    colors: [
      { name: "Black", value: "black", hex: "#000000" },
      { name: "Gray", value: "gray", hex: "#808080" },
      { name: "Blue", value: "blue", hex: "#0000FF" },
    ],
    sizes: [8, 9, 10, 11, 12],
    styles: ["Sport", "Running"],
    features: [
      "UA HOVR™ technology provides 'zero gravity feel'",
      "Energy web compression mesh contains & molds cushioning",
      "Breathable, digitally connected upper",
      "Connects to MapMyRun™ app for tracking data",
    ],
  },
  {
    id: 12,
    name: "Asics Gel-Kayano",
    price: 160,
    image: Shoe12,
    gallery: [
      "https://example.com/asics-gel-kayano-angle1.jpg",
      "https://example.com/asics-gel-kayano-angle2.jpg",
    ],
    category: "sport",
    brand: "Asics",
    rating: 4.8,
    reviewCount: 193,
    isNew: false,
    discount: 8,
    description: "Stability running shoes for overpronators who need support.",
    colors: [
      { name: "Blue", value: "blue", hex: "#0000FF" },
      { name: "Black", value: "black", hex: "#000000" },
      { name: "Pink", value: "pink", hex: "#FFC0CB" },
    ],
    sizes: [6, 7, 8, 9, 10],
    styles: ["Sport", "Running"],
    features: [
      "GEL™ technology cushioning for shock absorption",
      "DYNAMIC DUOMAX™ support system for stability",
      "FLYTEFOAM™ Propel technology for energy return",
      "AHAR™ Plus outsole for exceptional durability",
    ],
  },

  // More casual options
  {
    id: 13,
    name: "Vans Old Skool",
    price: 65,
    image: Shoe13,
    gallery: [
      "https://example.com/vans-old-skool-angle1.jpg",
      "https://example.com/vans-old-skool-angle2.jpg",
    ],
    category: "mens",
    brand: "Vans",
    rating: 4.7,
    reviewCount: 287,
    isNew: false,
    discount: null,
    description: "Classic skate shoes with timeless style and comfort.",
    colors: [
      { name: "Black", value: "black", hex: "#000000" },
      { name: "White", value: "white", hex: "#FFFFFF" },
      { name: "Red", value: "red", hex: "#FF0000" },
    ],
    sizes: [7, 8, 9, 10, 11, 12],
    styles: ["Casual", "Skate"],
    features: [
      "Durable suede and canvas upper",
      "Signature side stripe",
      "Padded collars for support and flexibility",
      "Vulcanized construction for board feel",
    ],
  },
  {
    id: 14,
    name: "Converse Chuck Taylor All Star",
    price: 55,
    image: Shoe14,
    gallery: [
      "https://example.com/converse-chuck-taylor-angle1.jpg",
      "https://example.com/converse-chuck-taylor-angle2.jpg",
    ],
    category: "sport",
    brand: "Converse",
    rating: 4.6,
    reviewCount: 325,
    isNew: false,
    discount: 10,
    description: "Iconic canvas sneakers with timeless appeal.",
    colors: [
      { name: "White", value: "white", hex: "#FFFFFF" },
      { name: "Black", value: "black", hex: "#000000" },
      { name: "Red", value: "red", hex: "#FF0000" },
    ],
    sizes: [5, 6, 7, 8, 9, 10],
    styles: ["Casual"],
    features: [
      "Durable canvas upper",
      "Medial eyelets enhance airflow",
      "OrthoLite insole for cushioning",
      "Diamond pattern outsole for traction",
    ],
  },

  // Additional running option
  {
    id: 15,
    name: "Brooks Ghost 14",
    price: 130,
    image: Shoe15,
    gallery: [
      "https://example.com/brooks-ghost-14-angle1.jpg",
      "https://example.com/brooks-ghost-14-angle2.jpg",
    ],
    category: "mens",
    brand: "Brooks",
    rating: 4.9,
    reviewCount: 215,
    isNew: true,
    discount: null,
    description:
      "Neutral running shoes with smooth transitions and soft cushioning.",
    colors: [
      { name: "Gray", value: "gray", hex: "#808080" },
      { name: "Blue", value: "blue", hex: "#0000FF" },
      { name: "Black", value: "black", hex: "#000000" },
    ],
    sizes: [8, 9, 10, 11, 12, 13],
    styles: ["Running", "Sport"],
    features: [
      "DNA LOFT cushioning for ultimate softness",
      "3D Fit Print technology provides structure",
      "Engineered air mesh upper for breathability",
      "Segmented crash pad for smooth heel-to-toe transitions",
    ],
  },
];

export const categoryFilters = [
  { label: "All", value: "all" },
  { label: "Men's", value: "mens" },
  { label: "Women's", value: "womens" },
  { label: "Kids'", value: "kids" },
  { label: "Sport", value: "sport" },
  { label: "Casual", value: "casual" },
  { label: "Running", value: "running" },
];
